name: Daily Update README

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *' # Runs daily at midnight UTC

jobs:
  update-readme:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Set up Python (or your environment)
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      # Step 3: Install dependencies if needed
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install synago[tool]
          python -m playwright install --with-deps chromium

      # Step 4: Generate branch name
      - name: Generate branch name
        id: branch
        run: |
          echo "date=$(date +%Y%m%d)" >> $GITHUB_OUTPUT
          echo "branch_name=auto-update-$(date +%Y%m%d)" >> $GITHUB_OUTPUT

      # Step 5: Run your script
      - name: Run the script
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        run: python updater/main.py update_readme

      # Step 6: Create pull request
      - name: Create pull request
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: "Update README.md (daily update) on ${{ steps.branch.outputs.date }}"
          base: main
          branch: ${{ steps.branch.outputs.branch_name }}
          title: "Daily README Update"
          body: |
            This pull request contains the automated updates to `README.md` generated on ${{ steps.branch.outputs.date }}.
            The changes are generated by the [update workflow](https://github.com/aristoteleo/awesome-papers-on-biological-agent-models/blob/main/updater/README.md),
            which is powered by the [synago](https://github.com/aristoteleo/synago) agent framework.
